Muda o avaliador de acessibilidade
betrybe/sd-0x-project-lessons-learned pull request #15
Opened 2021-04-28 15:09 UTC by paulohbsimoes

2021-05-04 11:47 UTC, fndcaique requested changes
@paulohbsimoes, fiz um teste não seguindo a sequência (h1 -> (h1 | h2), h2 -> (h2 | h3), ...), que significa que após um hn dentro uma sessão, o próximo heading deve ser um outro hn ou um hn+1, ou seja, após um h1, só pode ter um outro h1 ou um h2, não podemos pular para o h3, mas o teste não pega esse erro 😔

2021-05-04 11:47 UTC, fndcaique commented on cypress/integration/project.spec.js
> +      .runAllAccessibilityTests()
Dá forma como está é necessário estar rodando com o live server. Não seria melhor utilizar o código abaixo, como nos outros `it`s?
```suggestion
    cy.setUpContinuum('continuum/continuum.conf.js');
    cy.visit('/');
  });

  it('Testing', () => {
      cy.runAllAccessibilityTests()
```

2021-05-05 11:14 UTC, paulohbsimoes commented
> @paulohbsimoes, fiz um teste não seguindo a sequência (h1 -> (h1 | h2), h2 -> (h2 | h3), ...), que significa que após um hn dentro uma sessão, o próximo heading deve ser um outro hn ou um hn+1, ou seja, após um h1, só pode ter um outro h1 ou um h2, não podemos pular para o h3, mas o teste não pega esse erro

Excelente dica @fndcaique, obrigado! Vou verificar a questão dos headers :rocket:

2021-05-10 14:23 UTC, closed without merging

2021-05-10 14:24 UTC, paulohbsimoes commented
Foi encontrada uma alternativa melhor. Usamos o site: http://squizlabs.github.io/HTML_CodeSniffer/