[CONTENT REVIEW] 3.5 - Atualização do Readme
betrybe/sd-0x-project-lessons-learned pull request #7
Opened 2021-01-05 14:54 UTC by LucasSGomide

[Staged Repo](https://github.com/betrybe/sd-0x-project-lessons-learned-stg/pull/1)
[Tests Repo](https://github.com/betrybe/sd-0x-project-lessons-learned-tests/pull/3)
Closes https://github.com/betrybe/course/issues/2585

2021-01-07 12:45 UTC, cleytonoliveira commented on README.md
> +Nesse projeto, você será capaz de:
```suggestion
Neste projeto, você será capaz de:
```

2021-01-07 14:09 UTC, cleytonoliveira requested changes
Senti falta dos itens: 
- Avisos finais;
- Code climate ou linter?

Sugiro dar uma olha no padrão que os meninos criaram ou projetos que já estão seguindo o padrão:
- [Facebook](https://github.com/betrybe/sd-0x-project-facebook-signup)
- [Modelo dos Meninos de Front](https://gist.github.com/LizzardMedeiros/81d758d23e6ce085c8e58c7a5394195d)

2021-01-08 12:11 UTC, LucasSGomide commented on README.md
> +- [Instruções para entregar seu projeto](#instruções-para-entregar-seu-projeto)
Resolvido, boa !

2021-01-10 17:36 UTC, roziscoding commented
Tem um requisito que não está passando em staging. Precisamos ver o que é. Se for o caso, precisamos alterar a rúbrica do projeto também

2021-01-18 12:49 UTC, cleytonoliveira commented on README.md
> +- [Instruções para entregar seu projeto](#instruções-para-entregar-seu-projeto)
Acredito que não tem tópico sobre esta questão, não seria interessante deletar?

2021-01-18 12:54 UTC, cleytonoliveira requested changes

2021-01-18 12:54 UTC, cleytonoliveira commented on README.md
> +    - [1. Adicione uma cor de fundo específica para a página](#1.-adicione-uma-cor-de-fundo-específica-para-a-página)
O link não esta funcionando

2021-01-18 12:54 UTC, cleytonoliveira commented on README.md
> +    - [4. Adicione uma lista de lições aprendidas à página](#4-adicione-uma-lista-de-lições-aprendidas-a-página)
Também não esta funcionando

2021-01-18 12:54 UTC, cleytonoliveira commented on README.md
> +    - [8. Crie um artigo sobre seu aprendizado](#8-crie-um-artigo-sobre-seu-aprendizado)
Também não esta funcionando

2021-01-19 13:30 UTC, cleytonoliveira approved these changes

2021-01-20 07:34 UTC, roziscoding approved these changes
LGTM :shipit:

2021-01-29 12:56 UTC, merged